name = "Bluetooth disabled on sleep"
description = """\
Disable bluetooth on sleep, and enable it again when waking up. \
Helpful for macOS, which is notorious for draining battery from chatty \
Bluetooth devices."""

[[trigger]]
kind = "power"

[[condition]]
kind = "shell"
script = "true"

[[execute]]
kind = "shell"
script = "blueutil --power 0"

[[failure]]
kind = "shell"
# Send a local email (with `sendmail`) to tell us about it.
script = """\
printf '%s\n' 'Subject: Bluetooth management on sleep/wake failed' \
       '' \
       'Failed trying to manage Bluetooth during $action! See $LOG for details.' \
| sendmail $USER \
"""
