name = "Hello World"
description = "A very basic example"

[[triggers]]
kind = "cron"
cron = "1/4 * * * * *"

[[conditions]]
kind = "shell"
script = "true"

[[executors]]
kind = "shell"
script = "ls -al"

[[failures]]
kind = "shell"
script = "echo 'There was an error!'"
